name: yarn-prettier

on:
  push:
    branches: [ develop ]
#  schedule:
#    - cron: "0 1 * * 1"

jobs:
  yarn-prettier:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Setup ssh private key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - id: automerge
      name: Merge Pull request
      uses: "pascalgn/automerge-action@v0.15.2"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST: "8"
        LOG: "DEBUG"  # or "DEBUG"
