name: yarn-prettier

on:
  push:
    branches: [ develop ]
#  schedule:
#    - cron: "0 1 * * 1"

jobs:
  yarn-prettier:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Setup ssh private key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - id: open-pr
      name: Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ${{ env.SOURCE_BRANCH }}
        destination_branch: develop
        pr_title: "Auto Yarn Prettier"
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "roostinghawk"
        pr_assignee: "CloneableX"
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: output-url
      run: echo ${{steps.open-pr.outputs.pr_url}}
    - name: output-number
      run: echo ${{steps.open-pr.outputs.pr_number}}
    - name: output-has-changed-files
      run: echo ${{steps.open-pr.outputs.has_changed_files}}
