name: yarn-prettier

on:
  push:
    branches: [ develop ]
#  schedule:
#    - cron: "0 1 * * 1"

jobs:
  yarn-prettier:

    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Setup ssh private key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - uses: reitermarkus/automerge@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
